development:
  adapter: postgresql
  encoding: utf8
  username: FWallace
  database: influencers_development
  pool: 2
  url: <%= ENV['DATABASE_URL'] %>

test:
  adapter: postgresql
  encoding: utf8
  database: influencers_test
  pool: 2
  url: <%= ENV['DATABASE_URL'] %>

production:
  adapter: postgresql
  encoding: utf8
  database: influencers_production
  pool: 2
  url: <%= ENV['DATABASE_URL'] %>
  #username: <%= ENV['PG_USER'] %>
  #password: <%= ENV['PG_PASS'] %>
  #host: localhost